### ISSUE TITLE
Adding "Remember Me" Setting?

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#30] opened 2019-09-16 19:56 UTC
hi

Everyday i have type in my login and password.  Is there way to add check box "Remember Me", like what Sonarr has?

thanks.

![image](https://user-images.githubusercontent.com/33842064/64988891-487c5780-d881-11e9-9d88-622d208c5d68.png)

**Comment by barbequesauce** [comment] 2019-09-16 19:57
Duplicate of #29

**Closed by barbequesauce** 2019-09-16 19:57 UTC
